version: '3'
services:
  webhook:
    build:
      context: .
      dockerfile: Dockerfile 
    ports:
      - "8080:8080" 
    networks:
      - app-network

  ngrok:
    image: ngrok/ngrok:latest
    environment:
      - NGROK_AUTHTOKEN=''
    command: http webhook:8080
    networks:
      - app-network
    ports:
      - "4040:4040"

networks:
  app-network:
    driver: bridge
